[env]
_.file = { path = '.env.local', redact = true }

[tools]
go = "1.24.5"

[tasks.build-void]
description = "Build the project to /dev/null"
run = "go build -o /dev/null"

[tasks.test]
description = "Run all tests"
depends = ["format"]
run = "go test"

[tasks.lint]
description = "Lint the project"
depends = ["format"]
run = "golangci-lint run"

[tasks.format]
description = "Format all files"
run = "gofumpt -l -w ."

[tasks.check]
description = "Run all checks"
depends = ["format", "lint", "test", "build-void"]
run = "echo '✅ All checks passed!'"
