[env]
_.file = { path = '.env.local', redact = true }

[tools]
go = "1.24.5"

[tasks.watch]
description = "Watch for changes and rebuild the project"
file = "scripts/watch.sh"

[tasks.dev]
description = "Run the project and reload when the build changes"
file = "scripts/run.sh"
raw = true

[tasks.build-void]
description = "Build the project to /dev/null"
run = "go build -o /dev/null"

[tasks.test]
description = "Run all tests"
depends = ["format"]
run = "go test"

[tasks.lint]
description = "Lint the project"
depends = ["format"]
run = "golangci-lint run"

[tasks.format]
description = "Format all files"
run = "gofumpt -l -w ."

[tasks.release]
description = "Create a new release"
file = "scripts/release.sh"

[tasks.check]
description = "Run all checks"
depends = ["format", "lint", "test", "build-void"]
run = "echo '✅ All checks passed!'"
